<?php

namespace App\Domains\AI\Controllers\Api;

use App\Http\Controllers\Api\AdminApiController;
use App\Domains\AI\Models\AIConversation;
use App\Jobs\ProcessAIAnalysis;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class AIController extends AdminApiController
{
    public function index(): JsonResponse
    {
        $conversations = $this->restaurant()
            ->aiConversations()
            ->latest()
            ->paginate(20);

        return response()->json($conversations);
    }

    public function ask(Request $request): JsonResponse
    {
        $request->validate(['prompt' => ['required', 'string', 'max:2000']]);

        $restaurant = $this->restaurant();

        $conversation = $restaurant->aiConversations()->create([
            'user_id'  => auth()->id(),
            'prompt'   => $request->prompt,
            'response' => null,
        ]);

        // Dispatch async job; response will be updated when AI service replies
        ProcessAIAnalysis::dispatch($conversation);

        return response()->json([
            'data'    => $conversation,
            'message' => 'Your query is being processed. Check back shortly.',
        ], 202);
    }

    public function show(int $id): JsonResponse
    {
        $conversation = $this->restaurant()->aiConversations()->find($id);

        return $conversation
            ? response()->json(['data' => $conversation])
            : $this->notFound();
    }

    /**
     * Proactive alerts generated by the AI analysis pipeline.
     */
    public function alerts(): JsonResponse
    {
        $restaurant = $this->restaurant();

        $lowStock = $restaurant->inventoryItems()
            ->whereColumn('quantity', '<=', 'min_stock')
            ->where('status', 'active')
            ->get(['id', 'name', 'quantity', 'min_stock', 'unit']);

        $alerts = $lowStock->map(fn ($item) => [
            'type'    => 'low_stock',
            'level'   => 'warning',
            'message' => "Stock bajo: {$item->name} ({$item->quantity} {$item->unit} — mínimo {$item->min_stock})",
            'item_id' => $item->id,
        ]);

        return response()->json(['data' => $alerts]);
    }
}
